version: "2.1"

services:
  geoserver:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - 8080:8080
    env_file:
      - docker/env/geoserver.env
    depends_on:
      postgis:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
  postgis:
    image: kartoza/postgis:10.0-2.4
    volumes:
      - "postgis-data:/var/lib/postgresql"
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=golang
      - POSTGRES_PASS=golang
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - 5436:5432
    restart: unless-stopped
    healthcheck:
      test: "exit 0"
volumes:
  postgis-data:
  geoserver-data:
